/*
SQLyog Ultimate
MySQL - 5.7.33-0ubuntu0.16.04.1 : Database - siltap_base
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `yk_group_menu_aksi` */

CREATE TABLE `yk_group_menu_aksi` (
  `GroupMenuMenuAksiId` int(3) DEFAULT NULL,
  `GroupMenuGroupId` int(3) DEFAULT NULL,
  `GroupMenuSegmen` varchar(250) DEFAULT NULL,
  KEY `FK_ci_group_menu_dummy_menu` (`GroupMenuMenuAksiId`),
  KEY `FK_ci_group_menu_aksi` (`GroupMenuGroupId`),
  KEY `segen` (`GroupMenuSegmen`),
  CONSTRAINT `FK_ci_group_menu_aksi` FOREIGN KEY (`GroupMenuGroupId`) REFERENCES `yk_group` (`GroupId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ci_group_menu_aksi_aksi` FOREIGN KEY (`GroupMenuMenuAksiId`) REFERENCES `yk_menu_aksi` (`MenuAksiId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `yk_group_menu_aksi` */

insert  into `yk_group_menu_aksi`(`GroupMenuMenuAksiId`,`GroupMenuGroupId`,`GroupMenuSegmen`) values 
(1,1,'sistem/index'),
(2,1,'sistem/group/index'),
(3,1,'sistem/group/search'),
(4,1,'sistem/group/add'),
(5,1,'sistem/group/update'),
(6,1,'sistem/group/delete'),
(7,1,'sistem/user/index'),
(8,1,'sistem/user/search'),
(9,1,'sistem/user/add'),
(10,1,'sistem/user/update'),
(11,1,'sistem/user/delete'),
(12,1,'sistem/menu/index'),
(13,1,'sistem/menu/search'),
(14,1,'sistem/menu/add'),
(15,1,'sistem/menu/update'),
(16,1,'sistem/menu/delete'),
(17,1,'sistem/auth/index'),
(18,1,'sistem/auth/search'),
(19,1,'sistem/auth/update'),
(84,1,'master/index'),
(222,1,'persediaan/index'),
(231,1,'penggajian/rekapitulasi/index'),
(232,1,'penggajian/rekapitulasi/search'),
(233,1,'penggajian/rekapitulasi/add'),
(234,1,'penggajian/rekapitulasi/update'),
(235,1,'penggajian/rekapitulasi/delete'),
(236,1,'penggajian/rekapitulasi/detail'),
(237,1,'penggajian/rekapitulasi/cetak'),
(238,1,'penggajian/rekapitulasi/export'),
(247,1,'master/kecamatan/index'),
(248,1,'master/kecamatan/search'),
(249,1,'master/kecamatan/add'),
(250,1,'master/kecamatan/update'),
(251,1,'master/kecamatan/delete'),
(252,1,'master/kecamatan/detail'),
(253,1,'master/kecamatan/cetak'),
(254,1,'master/kecamatan/export'),
(255,1,'master/desa/index'),
(256,1,'master/desa/search'),
(257,1,'master/desa/add'),
(258,1,'master/desa/update'),
(259,1,'master/desa/delete'),
(260,1,'master/desa/detail'),
(261,1,'master/desa/cetak'),
(262,1,'master/desa/export'),
(263,1,'master/perangkat/index'),
(264,1,'master/perangkat/search'),
(265,1,'master/perangkat/add'),
(266,1,'master/perangkat/update'),
(267,1,'master/perangkat/delete'),
(268,1,'master/perangkat/detail'),
(269,1,'master/perangkat/cetak'),
(270,1,'master/perangkat/export'),
(272,1,'penggajian/permohonan/index'),
(273,1,'penggajian/permohonan/search'),
(274,1,'penggajian/permohonan/add'),
(275,1,'penggajian/permohonan/update'),
(276,1,'penggajian/permohonan/delete'),
(277,1,'penggajian/permohonan/detail'),
(278,1,'penggajian/permohonan/cetak'),
(279,1,'penggajian/permohonan/export'),
(222,5,'persediaan/index'),
(231,5,'penggajian/rekapitulasi/index'),
(232,5,'penggajian/rekapitulasi/search'),
(236,5,'penggajian/rekapitulasi/detail'),
(237,5,'penggajian/rekapitulasi/cetak'),
(238,5,'penggajian/rekapitulasi/export'),
(1,2,'sistem/index'),
(7,2,'sistem/user/index'),
(8,2,'sistem/user/search'),
(9,2,'sistem/user/add'),
(10,2,'sistem/user/update'),
(11,2,'sistem/user/delete'),
(84,2,'master/index'),
(222,2,'persediaan/index'),
(231,2,'penggajian/rekapitulasi/index'),
(232,2,'penggajian/rekapitulasi/search'),
(233,2,'penggajian/rekapitulasi/add'),
(234,2,'penggajian/rekapitulasi/update'),
(235,2,'penggajian/rekapitulasi/delete'),
(236,2,'penggajian/rekapitulasi/detail'),
(237,2,'penggajian/rekapitulasi/cetak'),
(238,2,'penggajian/rekapitulasi/export'),
(247,2,'master/kecamatan/index'),
(248,2,'master/kecamatan/search'),
(249,2,'master/kecamatan/add'),
(250,2,'master/kecamatan/update'),
(251,2,'master/kecamatan/delete'),
(252,2,'master/kecamatan/detail'),
(253,2,'master/kecamatan/cetak'),
(254,2,'master/kecamatan/export'),
(255,2,'master/desa/index'),
(256,2,'master/desa/search'),
(257,2,'master/desa/add'),
(258,2,'master/desa/update'),
(259,2,'master/desa/delete'),
(260,2,'master/desa/detail'),
(261,2,'master/desa/cetak'),
(262,2,'master/desa/export'),
(263,2,'master/perangkat/index'),
(264,2,'master/perangkat/search'),
(265,2,'master/perangkat/add'),
(266,2,'master/perangkat/update'),
(267,2,'master/perangkat/delete'),
(268,2,'master/perangkat/detail'),
(269,2,'master/perangkat/cetak'),
(270,2,'master/perangkat/export'),
(272,2,'penggajian/permohonan/index'),
(273,2,'penggajian/permohonan/search'),
(277,2,'penggajian/permohonan/detail'),
(278,2,'penggajian/permohonan/cetak'),
(279,2,'penggajian/permohonan/export'),
(280,2,'penggajian/rekapitulasi_edit/index'),
(281,2,'penggajian/rekapitulasi_edit/search'),
(282,2,'penggajian/rekapitulasi_edit/add'),
(283,2,'penggajian/rekapitulasi_edit/update'),
(284,2,'penggajian/rekapitulasi_edit/delete'),
(285,2,'penggajian/rekapitulasi_edit/detail'),
(286,2,'penggajian/rekapitulasi_edit/cetak'),
(287,2,'penggajian/rekapitulasi_edit/export'),
(84,3,'master/index'),
(222,3,'persediaan/index'),
(231,3,'penggajian/rekapitulasi/index'),
(232,3,'penggajian/rekapitulasi/search'),
(233,3,'penggajian/rekapitulasi/add'),
(234,3,'penggajian/rekapitulasi/update'),
(235,3,'penggajian/rekapitulasi/delete'),
(236,3,'penggajian/rekapitulasi/detail'),
(237,3,'penggajian/rekapitulasi/cetak'),
(238,3,'penggajian/rekapitulasi/export'),
(263,3,'master/perangkat/index'),
(264,3,'master/perangkat/search'),
(265,3,'master/perangkat/add'),
(266,3,'master/perangkat/update'),
(267,3,'master/perangkat/delete'),
(268,3,'master/perangkat/detail'),
(269,3,'master/perangkat/cetak'),
(270,3,'master/perangkat/export'),
(272,3,'penggajian/permohonan/index'),
(273,3,'penggajian/permohonan/search'),
(274,3,'penggajian/permohonan/add'),
(275,3,'penggajian/permohonan/update'),
(276,3,'penggajian/permohonan/delete'),
(277,3,'penggajian/permohonan/detail'),
(278,3,'penggajian/permohonan/cetak'),
(279,3,'penggajian/permohonan/export'),
(84,4,'master/index'),
(222,4,'persediaan/index'),
(231,4,'penggajian/rekapitulasi/index'),
(232,4,'penggajian/rekapitulasi/search'),
(233,4,'penggajian/rekapitulasi/add'),
(234,4,'penggajian/rekapitulasi/update'),
(235,4,'penggajian/rekapitulasi/delete'),
(236,4,'penggajian/rekapitulasi/detail'),
(237,4,'penggajian/rekapitulasi/cetak'),
(238,4,'penggajian/rekapitulasi/export'),
(247,4,'master/kecamatan/index'),
(248,4,'master/kecamatan/search'),
(250,4,'master/kecamatan/update'),
(252,4,'master/kecamatan/detail'),
(253,4,'master/kecamatan/cetak'),
(254,4,'master/kecamatan/export'),
(255,4,'master/desa/index'),
(256,4,'master/desa/search'),
(258,4,'master/desa/update'),
(260,4,'master/desa/detail'),
(261,4,'master/desa/cetak'),
(262,4,'master/desa/export'),
(263,4,'master/perangkat/index'),
(264,4,'master/perangkat/search'),
(265,4,'master/perangkat/add'),
(266,4,'master/perangkat/update'),
(267,4,'master/perangkat/delete'),
(268,4,'master/perangkat/detail'),
(269,4,'master/perangkat/cetak'),
(270,4,'master/perangkat/export'),
(272,4,'penggajian/permohonan/index'),
(273,4,'penggajian/permohonan/search'),
(274,4,'penggajian/permohonan/add'),
(275,4,'penggajian/permohonan/update'),
(276,4,'penggajian/permohonan/delete'),
(277,4,'penggajian/permohonan/detail'),
(278,4,'penggajian/permohonan/cetak'),
(279,4,'penggajian/permohonan/export');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
